{% set version = "0.4.3" %}

package:
  name: george
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/george/george-{{ version }}.tar.gz
  sha256: 9bdc873d72f4ccfd06c20abc95da5c4184c77fb6225303a40202e9060a6e6bff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - pybind11
    - numpy
    - setuptools_scm
    - toml

  run:
    - python
    - scipy
    - setuptools  # [win]
    - vs2015_runtime  # [win]

test:
  imports:
    - george

about:
  home: https://github.com/dfm/george
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast and flexible Gaussian Process regression in Python
  doc_url: http://george.readthedocs.io/
  dev_url: https://github.com/dfm/george

extra:
  recipe-maintainers:
    - hellovenkat
    - scopatz
    - dfm
