provider:
  win: azure
  linux_aarch64: default
conda_forge_output_validation: true
build_platform: {osx_arm64: osx_64}
test: native_and_emulated
github:
  branch_name: main
  tooling_branch_name: main
